### ISSUE TITLE
In Youth Explorer, it is not possible to switch to the 2011 data.

### ISSUE THREAD

**Issue by adieyal** [Code4SA/wazimap#119]
Users (including myself) search for a ward and confusingly cannot find it. I suggest that a warning is provided letting users know that the 2016 data does not contain wards. Also, there should be a link (including in the warning) that lets the user switch to 2016.

**Comment by xybrnet** [comment]
After discussing this we've determined the actual issue here was the response when using the search box taking too long, and a better user experience is required to show we're still awaiting a response.
