### ISSUE TITLE
Migration from Python 2.7 to Python 3?

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4SA/wazimap#146]
What happens when Python 2.7 is deprecated at the beginning of 2020? Is there a way forward to Python 3 for wazimap?

Warning from pip when installing requirements for wazimap:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. 
Please upgrade your Python as Python 2.7 won't be maintained after that date. 
A future version of pip will drop support for Python 2.7.
```

**Comment by DavidLemayian** [comment]
Hey @cliftonmcintosh . We made this Python 3 compatible here - https://github.com/CodeForAfrica/wazimap

@ebsuku is working to merge the `releases` branch to `master` and then we'll create a PR for it to be merged.

**Comment by knightebsuku** [comment]
Hi All.
I'm planning on moving the current master branch to release-v1.
Since the releases branch is v2, I'm just planning on moving it to master, perhaps force??
I'll update the readme files to inform the users which version is which.

**Comment by cliftonmcintosh** [comment]
Thanks for the information.
