### ISSUE TITLE
When will version 2.1.0 be released to PyPI?

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4SA/wazimap#154]
Thank you for your work maintaining this project. I am curious if/when the 2.X versions will be ready for release to the Python Package Index. We are interested in upgrading NepalMap to this version when it is ready.

**Comment by knightebsuku** [comment]
@cliftonmcintosh, I'll be working this week to add some documentation to the new version. Once that is complete I'll push up the package to pypi

**Comment by cliftonmcintosh** [comment]
Thank you for the information, @ebsuku.

**Comment by cliftonmcintosh** [comment]
@ebsuku 

I am following up to see if there is an update on the publishing of version 2.X. If it is not yet ready, are there any informal directions for updating? I would like to test out the update on NepalMap, even if it is not quite ready for publishing. This would allow me to discover and work through problems sooner.

**Comment by knightebsuku** [comment]
Hi @cliftonmcintosh. We've just released 2.X
Apologies for the delay, didn't really have time during the holidays.

**Comment by cliftonmcintosh** [comment]
Thank you, @ebsuku
