### ISSUE TITLE
'dict' object has no attribute 'itervalues'

### ISSUE THREAD

**Issue by divyamani1** [Code4SA/wazimap#156]
Wazimap v2.1.0 still uses dict.itervalues() to iterate through the values in dictionary (like FIELD_TABLES) instead of dict.values() as required by Python 3. 
![AttributeError at  locate ](https://user-images.githubusercontent.com/19853607/72994598-7bca8680-3e1f-11ea-88bc-a3668853ccd9.png)

**Comment by cliftonmcintosh** [comment]
#157 has been opened to replace .itervalues() with .values(). Is using the six library expected instead?

**Comment by divyamani1** [comment]
@cliftonmcintosh AFAIK, `six` library isn't used explicitly through the project but it probably is a dependency of some libraries.

**Comment by divyamani1** [comment]
#157 merged.
