### ISSUE TITLE
Error when trying to locate using co-ordinates

### ISSUE THREAD

**Issue by divyamani1** [Code4SA/wazimap#158]
When trying to access endpoint `/locate/` the following error occurs:

![KeyError at  locate ](https://user-images.githubusercontent.com/19853607/73661669-89ef9100-46c2-11ea-9264-d77e378fa0bf.png)

I'm working on the Nepalmap instance of Wazimap and trying to upgrade it to Python 3. I skimmed through the documentation but couldn't find much help (maybe I missed something). 

The function `get_locations_from_coords` (line 286) in `wazimap/geo.py` expects geometry features in following format:
``` 
{'properties': values, 'shape': values}
```
while currently it receives:
```
{'NP': {'properties': values, 'shape': values}}
```
and the above error occurs.

I edited the code in `geo.py` (line 286-291) as follows and it works fine.
```python
       for feature in features.values():
           code_value = list(feature.keys())[0]
           if feature['code_value']['shape'] and feature['code_value']['shape'].contains(p):
               geo = self.get_geography(feature['code_value']['properties']['code'],
                                        feature['code_value']['properties']['level'],
                                        version)
```

**Comment by divyamani1** [comment]
@ebsuku What do you think?

**Comment by knightebsuku** [comment]
Hi @divyamani1, I've not have time to look into this as of yet. 
I'll schedule some time early next week.
Could you create a pull request with your proposed changes?

**Comment by divyamani1** [comment]
@ebsuku Sure.
