### ISSUE TITLE
Bring map back to the index page

### ISSUE THREAD

**Issue by DavidLemayian** [Code4SA/wazimap#4]
The map was removed from the front page but it seems a user test at a workshop by @JustinArenstein showed that people engaged with the data faster when the map was at the front.

**Comment by longhotsummer** [comment]
Mostly done. The only problem is that the automatic zoom makes Kenya pretty small. So I'm looking at allowing a config option to center and zoom the homepage map correctly. That also means it loads before the county boundaries have to be loaded.

**Comment by DavidLemayian** [comment]
@longhotsummer Very cool! Can't wait. :)

**Comment by DavidLemayian** [comment]
Excellent work right there! As always..
