### ISSUE TITLE
Allow twitter logo to be overridden

### ISSUE THREAD

**Issue by amitness** [Code4SA/wazimap#55]
The twitter logo in the base template cannot be overridden. Currently if we want to modify it, we need to override the whole head block. 

I was making the link of twitter logo open in a new tab. 

A separate block for the twitter logo section can solve this.

Relevant code:*\* _base.html**

``` jinja
            {% if WAZIMAP.twitter %}
            <a class="wide-only" href="https://twitter.com/{{ WAZIMAP.twitter }}" title="{{ WAZIMAP.twitter }} on Twitter" target="_blank"><i class="fa fa-2x fa-twitter"></i></a>
            {% endif %}
```

**Comment by longhotsummer** [comment]
Thanks @studenton -- how about we just change the base template to open in a new tab? I think it's a good change in general.

There's a tradeoff between making every element in the template customisable, and having a template that's legible and reasonable to work with.

**Comment by amitness** [comment]
Thanks @longhotsummer. That will do.
