### ISSUE TITLE
Make GDAL an optional install

### ISSUE THREAD

**Issue by longhotsummer** [Code4SA/wazimap#71]
GDAL is a mission to install (see for example #51) and makes it hard to install Wazimap for development and on environments like Travis.

Currently, GDAL is required for download functionality and for finding areas that contain a lat-long coordinate. These aren't critical for development.

I suggest we add an install target like ``pip install wazimap[gdal]`` that provides the dependency, but doesn't by default.

In addition, to help people understand and migrate, print a warning when the server starts up and GDAL isn't detected. Perhaps also during install.

- [x] test with GDAL 1.10 on 14.04
- [x] test with GDAL >= 2.0 on 16.04

**Comment by longhotsummer** [comment]
Tracking this in the gdal-optional branch https://github.com/Code4SA/wazimap/tree/gdal-optional

**Comment by matiasf** [comment]
Hi Greg,

I have seen this ticket today and I hope you can help me. I configure gdal on a Vagrant file with the instructions you give me time ago, the problem now is the repository you send me now have a version > 2.0. For this reason my virtual machine isn't working anymore.

I have tried downgrade Ubuntu to precise but the version is 1.10. None of this versions is working with wazimap.

I have spend days trying to fix it but without result. Can you help me with this?

Thanks,
Matías.

**Comment by longhotsummer** [comment]
Hi @matiasf -- do you mean gdal's version is > 2.0?

**Comment by matiasf** [comment]
The ppa now have have 2.1 for xenial and trusty and 1.10.0 precise right now.
https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa

**Comment by longhotsummer** [comment]
@matiasf I have released version 0.7.0 which makes GDAL an optional install, and warns when it can't find GDAL. It also supports GDAL 1.x and 2.x.

Please try version wazimap==0.7.0 and let me know if it works?

**Comment by longhotsummer** [comment]
@matiasf Please use 0.7.1 instead, that makes Shapely optional, too.

**Comment by matiasf** [comment]
Thank @longhotsummer I'm going to try with this version, thanks a lot.
