### ISSUE TITLE
Where are you getting your Census Data from

### ISSUE THREAD

**Issue by Emilio105** [Code4SA/wazimap#73]
Hi

Was just wondering where are you getting your census data from and how are you linking it spatially to wards. Would be a great help if you could provide where and how you are getting this data?

Thanks

**Comment by longhotsummer** [comment]
Hi. We get our data directly from [Stats SA](http://www.statssa.gov.za/), which they provide at national, provincial, municipal and ward level. Their primary tool available to the public is SuperWEB:  http://interactive2.statssa.gov.za/webapi

We download that data in CSV form and then pull it into our database, where it's keyed off of the geography code (ward id, municipality id, etc.)
